// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: manual_control.proto

package manual_control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Possible results returned for manual control requests.
type ManualControlResult_Result int32

const (
	ManualControlResult_RESULT_UNKNOWN            ManualControlResult_Result = 0 // Unknown result
	ManualControlResult_RESULT_SUCCESS            ManualControlResult_Result = 1 // Request was successful
	ManualControlResult_RESULT_NO_SYSTEM          ManualControlResult_Result = 2 // No system is connected
	ManualControlResult_RESULT_CONNECTION_ERROR   ManualControlResult_Result = 3 // Connection error
	ManualControlResult_RESULT_BUSY               ManualControlResult_Result = 4 // Vehicle is busy
	ManualControlResult_RESULT_COMMAND_DENIED     ManualControlResult_Result = 5 // Command refused by vehicle
	ManualControlResult_RESULT_TIMEOUT            ManualControlResult_Result = 6 // Request timed out
	ManualControlResult_RESULT_INPUT_OUT_OF_RANGE ManualControlResult_Result = 7 // Input out of range
	ManualControlResult_RESULT_INPUT_NOT_SET      ManualControlResult_Result = 8 // No Input set
)

// Enum value maps for ManualControlResult_Result.
var (
	ManualControlResult_Result_name = map[int32]string{
		0: "RESULT_UNKNOWN",
		1: "RESULT_SUCCESS",
		2: "RESULT_NO_SYSTEM",
		3: "RESULT_CONNECTION_ERROR",
		4: "RESULT_BUSY",
		5: "RESULT_COMMAND_DENIED",
		6: "RESULT_TIMEOUT",
		7: "RESULT_INPUT_OUT_OF_RANGE",
		8: "RESULT_INPUT_NOT_SET",
	}
	ManualControlResult_Result_value = map[string]int32{
		"RESULT_UNKNOWN":            0,
		"RESULT_SUCCESS":            1,
		"RESULT_NO_SYSTEM":          2,
		"RESULT_CONNECTION_ERROR":   3,
		"RESULT_BUSY":               4,
		"RESULT_COMMAND_DENIED":     5,
		"RESULT_TIMEOUT":            6,
		"RESULT_INPUT_OUT_OF_RANGE": 7,
		"RESULT_INPUT_NOT_SET":      8,
	}
)

func (x ManualControlResult_Result) Enum() *ManualControlResult_Result {
	p := new(ManualControlResult_Result)
	*p = x
	return p
}

func (x ManualControlResult_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ManualControlResult_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_manual_control_proto_enumTypes[0].Descriptor()
}

func (ManualControlResult_Result) Type() protoreflect.EnumType {
	return &file_manual_control_proto_enumTypes[0]
}

func (x ManualControlResult_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ManualControlResult_Result.Descriptor instead.
func (ManualControlResult_Result) EnumDescriptor() ([]byte, []int) {
	return file_manual_control_proto_rawDescGZIP(), []int{6, 0}
}

type StartPositionControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPositionControlRequest) Reset() {
	*x = StartPositionControlRequest{}
	mi := &file_manual_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPositionControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPositionControlRequest) ProtoMessage() {}

func (x *StartPositionControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manual_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPositionControlRequest.ProtoReflect.Descriptor instead.
func (*StartPositionControlRequest) Descriptor() ([]byte, []int) {
	return file_manual_control_proto_rawDescGZIP(), []int{0}
}

type StartPositionControlResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ManualControlResult *ManualControlResult   `protobuf:"bytes,1,opt,name=manual_control_result,json=manualControlResult,proto3" json:"manual_control_result,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StartPositionControlResponse) Reset() {
	*x = StartPositionControlResponse{}
	mi := &file_manual_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPositionControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPositionControlResponse) ProtoMessage() {}

func (x *StartPositionControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manual_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPositionControlResponse.ProtoReflect.Descriptor instead.
func (*StartPositionControlResponse) Descriptor() ([]byte, []int) {
	return file_manual_control_proto_rawDescGZIP(), []int{1}
}

func (x *StartPositionControlResponse) GetManualControlResult() *ManualControlResult {
	if x != nil {
		return x.ManualControlResult
	}
	return nil
}

type StartAltitudeControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAltitudeControlRequest) Reset() {
	*x = StartAltitudeControlRequest{}
	mi := &file_manual_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAltitudeControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAltitudeControlRequest) ProtoMessage() {}

func (x *StartAltitudeControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manual_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAltitudeControlRequest.ProtoReflect.Descriptor instead.
func (*StartAltitudeControlRequest) Descriptor() ([]byte, []int) {
	return file_manual_control_proto_rawDescGZIP(), []int{2}
}

type StartAltitudeControlResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ManualControlResult *ManualControlResult   `protobuf:"bytes,1,opt,name=manual_control_result,json=manualControlResult,proto3" json:"manual_control_result,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StartAltitudeControlResponse) Reset() {
	*x = StartAltitudeControlResponse{}
	mi := &file_manual_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAltitudeControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAltitudeControlResponse) ProtoMessage() {}

func (x *StartAltitudeControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manual_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAltitudeControlResponse.ProtoReflect.Descriptor instead.
func (*StartAltitudeControlResponse) Descriptor() ([]byte, []int) {
	return file_manual_control_proto_rawDescGZIP(), []int{3}
}

func (x *StartAltitudeControlResponse) GetManualControlResult() *ManualControlResult {
	if x != nil {
		return x.ManualControlResult
	}
	return nil
}

type SetManualControlInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"` // value between -1. to 1. negative -> backwards, positive -> forwards
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"` // value between -1. to 1. negative -> left, positive -> right
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"` // value between -1. to 1. negative -> down, positive -> up (usually for now, for multicopter 0 to 1 is expected)
	R             float32                `protobuf:"fixed32,4,opt,name=r,proto3" json:"r,omitempty"` // value between -1. to 1. negative -> turn anti-clockwise (towards the left), positive -> turn clockwise (towards the right)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetManualControlInputRequest) Reset() {
	*x = SetManualControlInputRequest{}
	mi := &file_manual_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetManualControlInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetManualControlInputRequest) ProtoMessage() {}

func (x *SetManualControlInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manual_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetManualControlInputRequest.ProtoReflect.Descriptor instead.
func (*SetManualControlInputRequest) Descriptor() ([]byte, []int) {
	return file_manual_control_proto_rawDescGZIP(), []int{4}
}

func (x *SetManualControlInputRequest) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SetManualControlInputRequest) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *SetManualControlInputRequest) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *SetManualControlInputRequest) GetR() float32 {
	if x != nil {
		return x.R
	}
	return 0
}

type SetManualControlInputResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ManualControlResult *ManualControlResult   `protobuf:"bytes,1,opt,name=manual_control_result,json=manualControlResult,proto3" json:"manual_control_result,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SetManualControlInputResponse) Reset() {
	*x = SetManualControlInputResponse{}
	mi := &file_manual_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetManualControlInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetManualControlInputResponse) ProtoMessage() {}

func (x *SetManualControlInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manual_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetManualControlInputResponse.ProtoReflect.Descriptor instead.
func (*SetManualControlInputResponse) Descriptor() ([]byte, []int) {
	return file_manual_control_proto_rawDescGZIP(), []int{5}
}

func (x *SetManualControlInputResponse) GetManualControlResult() *ManualControlResult {
	if x != nil {
		return x.ManualControlResult
	}
	return nil
}

// Result type.
type ManualControlResult struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Result        ManualControlResult_Result `protobuf:"varint,1,opt,name=result,proto3,enum=mavsdk.rpc.manual_control.ManualControlResult_Result" json:"result,omitempty"` // Result enum value
	ResultStr     string                     `protobuf:"bytes,2,opt,name=result_str,json=resultStr,proto3" json:"result_str,omitempty"`                                     // Human-readable English string describing the result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualControlResult) Reset() {
	*x = ManualControlResult{}
	mi := &file_manual_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualControlResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualControlResult) ProtoMessage() {}

func (x *ManualControlResult) ProtoReflect() protoreflect.Message {
	mi := &file_manual_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualControlResult.ProtoReflect.Descriptor instead.
func (*ManualControlResult) Descriptor() ([]byte, []int) {
	return file_manual_control_proto_rawDescGZIP(), []int{6}
}

func (x *ManualControlResult) GetResult() ManualControlResult_Result {
	if x != nil {
		return x.Result
	}
	return ManualControlResult_RESULT_UNKNOWN
}

func (x *ManualControlResult) GetResultStr() string {
	if x != nil {
		return x.ResultStr
	}
	return ""
}

var File_manual_control_proto protoreflect.FileDescriptor

const file_manual_control_proto_rawDesc = "" +
	"\n" +
	"\x14manual_control.proto\x12\x19mavsdk.rpc.manual_control\x1a\x14mavsdk_options.proto\"\x1d\n" +
	"\x1bStartPositionControlRequest\"\x82\x01\n" +
	"\x1cStartPositionControlResponse\x12b\n" +
	"\x15manual_control_result\x18\x01 \x01(\v2..mavsdk.rpc.manual_control.ManualControlResultR\x13manualControlResult\"\x1d\n" +
	"\x1bStartAltitudeControlRequest\"\x82\x01\n" +
	"\x1cStartAltitudeControlResponse\x12b\n" +
	"\x15manual_control_result\x18\x01 \x01(\v2..mavsdk.rpc.manual_control.ManualControlResultR\x13manualControlResult\"V\n" +
	"\x1cSetManualControlInputRequest\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12\f\n" +
	"\x01r\x18\x04 \x01(\x02R\x01r\"\x83\x01\n" +
	"\x1dSetManualControlInputResponse\x12b\n" +
	"\x15manual_control_result\x18\x01 \x01(\v2..mavsdk.rpc.manual_control.ManualControlResultR\x13manualControlResult\"\xe2\x02\n" +
	"\x13ManualControlResult\x12M\n" +
	"\x06result\x18\x01 \x01(\x0e25.mavsdk.rpc.manual_control.ManualControlResult.ResultR\x06result\x12\x1d\n" +
	"\n" +
	"result_str\x18\x02 \x01(\tR\tresultStr\"\xdc\x01\n" +
	"\x06Result\x12\x12\n" +
	"\x0eRESULT_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eRESULT_SUCCESS\x10\x01\x12\x14\n" +
	"\x10RESULT_NO_SYSTEM\x10\x02\x12\x1b\n" +
	"\x17RESULT_CONNECTION_ERROR\x10\x03\x12\x0f\n" +
	"\vRESULT_BUSY\x10\x04\x12\x19\n" +
	"\x15RESULT_COMMAND_DENIED\x10\x05\x12\x12\n" +
	"\x0eRESULT_TIMEOUT\x10\x06\x12\x1d\n" +
	"\x19RESULT_INPUT_OUT_OF_RANGE\x10\a\x12\x18\n" +
	"\x14RESULT_INPUT_NOT_SET\x10\b2\xc1\x03\n" +
	"\x14ManualControlService\x12\x89\x01\n" +
	"\x14StartPositionControl\x126.mavsdk.rpc.manual_control.StartPositionControlRequest\x1a7.mavsdk.rpc.manual_control.StartPositionControlResponse\"\x00\x12\x89\x01\n" +
	"\x14StartAltitudeControl\x126.mavsdk.rpc.manual_control.StartAltitudeControlRequest\x1a7.mavsdk.rpc.manual_control.StartAltitudeControlResponse\"\x00\x12\x90\x01\n" +
	"\x15SetManualControlInput\x127.mavsdk.rpc.manual_control.SetManualControlInputRequest\x1a8.mavsdk.rpc.manual_control.SetManualControlInputResponse\"\x04\x80\xb5\x18\x01B&B\x12ManualControlProtoZ\x10.;manual_controlb\x06proto3"

var (
	file_manual_control_proto_rawDescOnce sync.Once
	file_manual_control_proto_rawDescData []byte
)

func file_manual_control_proto_rawDescGZIP() []byte {
	file_manual_control_proto_rawDescOnce.Do(func() {
		file_manual_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manual_control_proto_rawDesc), len(file_manual_control_proto_rawDesc)))
	})
	return file_manual_control_proto_rawDescData
}

var file_manual_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_manual_control_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_manual_control_proto_goTypes = []any{
	(ManualControlResult_Result)(0),       // 0: mavsdk.rpc.manual_control.ManualControlResult.Result
	(*StartPositionControlRequest)(nil),   // 1: mavsdk.rpc.manual_control.StartPositionControlRequest
	(*StartPositionControlResponse)(nil),  // 2: mavsdk.rpc.manual_control.StartPositionControlResponse
	(*StartAltitudeControlRequest)(nil),   // 3: mavsdk.rpc.manual_control.StartAltitudeControlRequest
	(*StartAltitudeControlResponse)(nil),  // 4: mavsdk.rpc.manual_control.StartAltitudeControlResponse
	(*SetManualControlInputRequest)(nil),  // 5: mavsdk.rpc.manual_control.SetManualControlInputRequest
	(*SetManualControlInputResponse)(nil), // 6: mavsdk.rpc.manual_control.SetManualControlInputResponse
	(*ManualControlResult)(nil),           // 7: mavsdk.rpc.manual_control.ManualControlResult
}
var file_manual_control_proto_depIdxs = []int32{
	7, // 0: mavsdk.rpc.manual_control.StartPositionControlResponse.manual_control_result:type_name -> mavsdk.rpc.manual_control.ManualControlResult
	7, // 1: mavsdk.rpc.manual_control.StartAltitudeControlResponse.manual_control_result:type_name -> mavsdk.rpc.manual_control.ManualControlResult
	7, // 2: mavsdk.rpc.manual_control.SetManualControlInputResponse.manual_control_result:type_name -> mavsdk.rpc.manual_control.ManualControlResult
	0, // 3: mavsdk.rpc.manual_control.ManualControlResult.result:type_name -> mavsdk.rpc.manual_control.ManualControlResult.Result
	1, // 4: mavsdk.rpc.manual_control.ManualControlService.StartPositionControl:input_type -> mavsdk.rpc.manual_control.StartPositionControlRequest
	3, // 5: mavsdk.rpc.manual_control.ManualControlService.StartAltitudeControl:input_type -> mavsdk.rpc.manual_control.StartAltitudeControlRequest
	5, // 6: mavsdk.rpc.manual_control.ManualControlService.SetManualControlInput:input_type -> mavsdk.rpc.manual_control.SetManualControlInputRequest
	2, // 7: mavsdk.rpc.manual_control.ManualControlService.StartPositionControl:output_type -> mavsdk.rpc.manual_control.StartPositionControlResponse
	4, // 8: mavsdk.rpc.manual_control.ManualControlService.StartAltitudeControl:output_type -> mavsdk.rpc.manual_control.StartAltitudeControlResponse
	6, // 9: mavsdk.rpc.manual_control.ManualControlService.SetManualControlInput:output_type -> mavsdk.rpc.manual_control.SetManualControlInputResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_manual_control_proto_init() }
func file_manual_control_proto_init() {
	if File_manual_control_proto != nil {
		return
	}
	file_mavsdk_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manual_control_proto_rawDesc), len(file_manual_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manual_control_proto_goTypes,
		DependencyIndexes: file_manual_control_proto_depIdxs,
		EnumInfos:         file_manual_control_proto_enumTypes,
		MessageInfos:      file_manual_control_proto_msgTypes,
	}.Build()
	File_manual_control_proto = out.File
	file_manual_control_proto_goTypes = nil
	file_manual_control_proto_depIdxs = nil
}
