// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: winch.proto

package winch

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Winch Action type.
type WinchAction int32

const (
	WinchAction_WINCH_ACTION_RELAXED                 WinchAction = 0 // Allow motor to freewheel
	WinchAction_WINCH_ACTION_RELATIVE_LENGTH_CONTROL WinchAction = 1 // Wind or unwind specified length of line, optionally using specified rate
	WinchAction_WINCH_ACTION_RATE_CONTROL            WinchAction = 2 // Wind or unwind line at specified rate
	WinchAction_WINCH_ACTION_LOCK                    WinchAction = 3 // Perform the locking sequence to relieve motor while in the fully retracted position
	WinchAction_WINCH_ACTION_DELIVER                 WinchAction = 4 // Sequence of drop, slow down, touch down, reel up, lock
	WinchAction_WINCH_ACTION_HOLD                    WinchAction = 5 // Engage motor and hold current position
	WinchAction_WINCH_ACTION_RETRACT                 WinchAction = 6 // Return the reel to the fully retracted position
	WinchAction_WINCH_ACTION_LOAD_LINE               WinchAction = 7 // Load the reel with line. The winch will calculate the total loaded length and stop when the tension exceeds a threshold
	WinchAction_WINCH_ACTION_ABANDON_LINE            WinchAction = 8 // Spool out the entire length of the line
	WinchAction_WINCH_ACTION_LOAD_PAYLOAD            WinchAction = 9 // Spools out just enough to present the hook to the user to load the payload
)

// Enum value maps for WinchAction.
var (
	WinchAction_name = map[int32]string{
		0: "WINCH_ACTION_RELAXED",
		1: "WINCH_ACTION_RELATIVE_LENGTH_CONTROL",
		2: "WINCH_ACTION_RATE_CONTROL",
		3: "WINCH_ACTION_LOCK",
		4: "WINCH_ACTION_DELIVER",
		5: "WINCH_ACTION_HOLD",
		6: "WINCH_ACTION_RETRACT",
		7: "WINCH_ACTION_LOAD_LINE",
		8: "WINCH_ACTION_ABANDON_LINE",
		9: "WINCH_ACTION_LOAD_PAYLOAD",
	}
	WinchAction_value = map[string]int32{
		"WINCH_ACTION_RELAXED":                 0,
		"WINCH_ACTION_RELATIVE_LENGTH_CONTROL": 1,
		"WINCH_ACTION_RATE_CONTROL":            2,
		"WINCH_ACTION_LOCK":                    3,
		"WINCH_ACTION_DELIVER":                 4,
		"WINCH_ACTION_HOLD":                    5,
		"WINCH_ACTION_RETRACT":                 6,
		"WINCH_ACTION_LOAD_LINE":               7,
		"WINCH_ACTION_ABANDON_LINE":            8,
		"WINCH_ACTION_LOAD_PAYLOAD":            9,
	}
)

func (x WinchAction) Enum() *WinchAction {
	p := new(WinchAction)
	*p = x
	return p
}

func (x WinchAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WinchAction) Descriptor() protoreflect.EnumDescriptor {
	return file_winch_proto_enumTypes[0].Descriptor()
}

func (WinchAction) Type() protoreflect.EnumType {
	return &file_winch_proto_enumTypes[0]
}

func (x WinchAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WinchAction.Descriptor instead.
func (WinchAction) EnumDescriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{0}
}

// Possible results returned for winch action requests.
type WinchResult_Result int32

const (
	WinchResult_RESULT_UNKNOWN     WinchResult_Result = 0 // Unknown result
	WinchResult_RESULT_SUCCESS     WinchResult_Result = 1 // Request was successful
	WinchResult_RESULT_NO_SYSTEM   WinchResult_Result = 2 // No system is connected
	WinchResult_RESULT_BUSY        WinchResult_Result = 3 // Temporarily rejected
	WinchResult_RESULT_TIMEOUT     WinchResult_Result = 4 // Request timed out
	WinchResult_RESULT_UNSUPPORTED WinchResult_Result = 5 // Action not supported
	WinchResult_RESULT_FAILED      WinchResult_Result = 6 // Action failed
)

// Enum value maps for WinchResult_Result.
var (
	WinchResult_Result_name = map[int32]string{
		0: "RESULT_UNKNOWN",
		1: "RESULT_SUCCESS",
		2: "RESULT_NO_SYSTEM",
		3: "RESULT_BUSY",
		4: "RESULT_TIMEOUT",
		5: "RESULT_UNSUPPORTED",
		6: "RESULT_FAILED",
	}
	WinchResult_Result_value = map[string]int32{
		"RESULT_UNKNOWN":     0,
		"RESULT_SUCCESS":     1,
		"RESULT_NO_SYSTEM":   2,
		"RESULT_BUSY":        3,
		"RESULT_TIMEOUT":     4,
		"RESULT_UNSUPPORTED": 5,
		"RESULT_FAILED":      6,
	}
)

func (x WinchResult_Result) Enum() *WinchResult_Result {
	p := new(WinchResult_Result)
	*p = x
	return p
}

func (x WinchResult_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WinchResult_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_winch_proto_enumTypes[1].Descriptor()
}

func (WinchResult_Result) Type() protoreflect.EnumType {
	return &file_winch_proto_enumTypes[1]
}

func (x WinchResult_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WinchResult_Result.Descriptor instead.
func (WinchResult_Result) EnumDescriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{24, 0}
}

type SubscribeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeStatusRequest) Reset() {
	*x = SubscribeStatusRequest{}
	mi := &file_winch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeStatusRequest) ProtoMessage() {}

func (x *SubscribeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeStatusRequest.ProtoReflect.Descriptor instead.
func (*SubscribeStatusRequest) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // The next 'winch status' state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_winch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

// Winch Status Flags.
//
// The status flags are defined in mavlink
// https://mavlink.io/en/messages/common.html#MAV_WINCH_STATUS_FLAG.
//
// Multiple status fields can be set simultaneously. Mavlink does
// not specify which states are mutually exclusive.
type StatusFlags struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Healthy        bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`                                     // Winch is healthy
	FullyRetracted bool                   `protobuf:"varint,2,opt,name=fully_retracted,json=fullyRetracted,proto3" json:"fully_retracted,omitempty"` // Winch line is fully retracted
	Moving         bool                   `protobuf:"varint,3,opt,name=moving,proto3" json:"moving,omitempty"`                                       // Winch motor is moving
	ClutchEngaged  bool                   `protobuf:"varint,4,opt,name=clutch_engaged,json=clutchEngaged,proto3" json:"clutch_engaged,omitempty"`    // Winch clutch is engaged allowing motor to move freely
	Locked         bool                   `protobuf:"varint,5,opt,name=locked,proto3" json:"locked,omitempty"`                                       // Winch is locked by locking mechanism
	Dropping       bool                   `protobuf:"varint,6,opt,name=dropping,proto3" json:"dropping,omitempty"`                                   // Winch is gravity dropping payload
	Arresting      bool                   `protobuf:"varint,7,opt,name=arresting,proto3" json:"arresting,omitempty"`                                 // Winch is arresting payload descent
	GroundSense    bool                   `protobuf:"varint,8,opt,name=ground_sense,json=groundSense,proto3" json:"ground_sense,omitempty"`          // Winch is using torque measurements to sense the ground
	Retracting     bool                   `protobuf:"varint,9,opt,name=retracting,proto3" json:"retracting,omitempty"`                               // Winch is returning to the fully retracted position
	Redeliver      bool                   `protobuf:"varint,10,opt,name=redeliver,proto3" json:"redeliver,omitempty"`                                // Winch is redelivering the payload. This is a failover state if the line tension goes above a threshold during RETRACTING.
	AbandonLine    bool                   `protobuf:"varint,11,opt,name=abandon_line,json=abandonLine,proto3" json:"abandon_line,omitempty"`         // Winch is abandoning the line and possibly payload. Winch unspools the entire calculated line length. This is a failover state from REDELIVER if the number of attempts exceeds a threshold.
	Locking        bool                   `protobuf:"varint,12,opt,name=locking,proto3" json:"locking,omitempty"`                                    // Winch is engaging the locking mechanism
	LoadLine       bool                   `protobuf:"varint,13,opt,name=load_line,json=loadLine,proto3" json:"load_line,omitempty"`                  // Winch is spooling on line
	LoadPayload    bool                   `protobuf:"varint,14,opt,name=load_payload,json=loadPayload,proto3" json:"load_payload,omitempty"`         // Winch is loading a payload
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusFlags) Reset() {
	*x = StatusFlags{}
	mi := &file_winch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusFlags) ProtoMessage() {}

func (x *StatusFlags) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusFlags.ProtoReflect.Descriptor instead.
func (*StatusFlags) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{2}
}

func (x *StatusFlags) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *StatusFlags) GetFullyRetracted() bool {
	if x != nil {
		return x.FullyRetracted
	}
	return false
}

func (x *StatusFlags) GetMoving() bool {
	if x != nil {
		return x.Moving
	}
	return false
}

func (x *StatusFlags) GetClutchEngaged() bool {
	if x != nil {
		return x.ClutchEngaged
	}
	return false
}

func (x *StatusFlags) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *StatusFlags) GetDropping() bool {
	if x != nil {
		return x.Dropping
	}
	return false
}

func (x *StatusFlags) GetArresting() bool {
	if x != nil {
		return x.Arresting
	}
	return false
}

func (x *StatusFlags) GetGroundSense() bool {
	if x != nil {
		return x.GroundSense
	}
	return false
}

func (x *StatusFlags) GetRetracting() bool {
	if x != nil {
		return x.Retracting
	}
	return false
}

func (x *StatusFlags) GetRedeliver() bool {
	if x != nil {
		return x.Redeliver
	}
	return false
}

func (x *StatusFlags) GetAbandonLine() bool {
	if x != nil {
		return x.AbandonLine
	}
	return false
}

func (x *StatusFlags) GetLocking() bool {
	if x != nil {
		return x.Locking
	}
	return false
}

func (x *StatusFlags) GetLoadLine() bool {
	if x != nil {
		return x.LoadLine
	}
	return false
}

func (x *StatusFlags) GetLoadPayload() bool {
	if x != nil {
		return x.LoadPayload
	}
	return false
}

// Status type.
type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeUsec      uint64                 `protobuf:"varint,1,opt,name=time_usec,json=timeUsec,proto3" json:"time_usec,omitempty"`             // Time in usec
	LineLengthM   float32                `protobuf:"fixed32,2,opt,name=line_length_m,json=lineLengthM,proto3" json:"line_length_m,omitempty"` // Length of the line in meters
	SpeedMS       float32                `protobuf:"fixed32,3,opt,name=speed_m_s,json=speedMS,proto3" json:"speed_m_s,omitempty"`             // Speed in meters per second
	TensionKg     float32                `protobuf:"fixed32,4,opt,name=tension_kg,json=tensionKg,proto3" json:"tension_kg,omitempty"`         // Tension in kilograms
	VoltageV      float32                `protobuf:"fixed32,5,opt,name=voltage_v,json=voltageV,proto3" json:"voltage_v,omitempty"`            // Voltage in volts
	CurrentA      float32                `protobuf:"fixed32,6,opt,name=current_a,json=currentA,proto3" json:"current_a,omitempty"`            // Current in amperes
	TemperatureC  int32                  `protobuf:"varint,7,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"` // Temperature in Celsius
	StatusFlags   *StatusFlags           `protobuf:"bytes,8,opt,name=status_flags,json=statusFlags,proto3" json:"status_flags,omitempty"`     // Status flags
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_winch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{3}
}

func (x *Status) GetTimeUsec() uint64 {
	if x != nil {
		return x.TimeUsec
	}
	return 0
}

func (x *Status) GetLineLengthM() float32 {
	if x != nil {
		return x.LineLengthM
	}
	return 0
}

func (x *Status) GetSpeedMS() float32 {
	if x != nil {
		return x.SpeedMS
	}
	return 0
}

func (x *Status) GetTensionKg() float32 {
	if x != nil {
		return x.TensionKg
	}
	return 0
}

func (x *Status) GetVoltageV() float32 {
	if x != nil {
		return x.VoltageV
	}
	return 0
}

func (x *Status) GetCurrentA() float32 {
	if x != nil {
		return x.CurrentA
	}
	return 0
}

func (x *Status) GetTemperatureC() int32 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

func (x *Status) GetStatusFlags() *StatusFlags {
	if x != nil {
		return x.StatusFlags
	}
	return nil
}

type RelaxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      uint32                 `protobuf:"varint,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelaxRequest) Reset() {
	*x = RelaxRequest{}
	mi := &file_winch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelaxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelaxRequest) ProtoMessage() {}

func (x *RelaxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelaxRequest.ProtoReflect.Descriptor instead.
func (*RelaxRequest) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{4}
}

func (x *RelaxRequest) GetInstance() uint32 {
	if x != nil {
		return x.Instance
	}
	return 0
}

type RelaxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinchResult   *WinchResult           `protobuf:"bytes,1,opt,name=winch_result,json=winchResult,proto3" json:"winch_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelaxResponse) Reset() {
	*x = RelaxResponse{}
	mi := &file_winch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelaxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelaxResponse) ProtoMessage() {}

func (x *RelaxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelaxResponse.ProtoReflect.Descriptor instead.
func (*RelaxResponse) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{5}
}

func (x *RelaxResponse) GetWinchResult() *WinchResult {
	if x != nil {
		return x.WinchResult
	}
	return nil
}

type RelativeLengthControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      uint32                 `protobuf:"varint,1,opt,name=instance,proto3" json:"instance,omitempty"`               // Instance ID of the winch addressed by this request
	LengthM       float32                `protobuf:"fixed32,2,opt,name=length_m,json=lengthM,proto3" json:"length_m,omitempty"` // Length of line to unwind or wind
	RateMS        float32                `protobuf:"fixed32,3,opt,name=rate_m_s,json=rateMS,proto3" json:"rate_m_s,omitempty"`  // Rate at which to wind or unwind the line
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelativeLengthControlRequest) Reset() {
	*x = RelativeLengthControlRequest{}
	mi := &file_winch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelativeLengthControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelativeLengthControlRequest) ProtoMessage() {}

func (x *RelativeLengthControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelativeLengthControlRequest.ProtoReflect.Descriptor instead.
func (*RelativeLengthControlRequest) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{6}
}

func (x *RelativeLengthControlRequest) GetInstance() uint32 {
	if x != nil {
		return x.Instance
	}
	return 0
}

func (x *RelativeLengthControlRequest) GetLengthM() float32 {
	if x != nil {
		return x.LengthM
	}
	return 0
}

func (x *RelativeLengthControlRequest) GetRateMS() float32 {
	if x != nil {
		return x.RateMS
	}
	return 0
}

type RelativeLengthControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinchResult   *WinchResult           `protobuf:"bytes,1,opt,name=winch_result,json=winchResult,proto3" json:"winch_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelativeLengthControlResponse) Reset() {
	*x = RelativeLengthControlResponse{}
	mi := &file_winch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelativeLengthControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelativeLengthControlResponse) ProtoMessage() {}

func (x *RelativeLengthControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelativeLengthControlResponse.ProtoReflect.Descriptor instead.
func (*RelativeLengthControlResponse) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{7}
}

func (x *RelativeLengthControlResponse) GetWinchResult() *WinchResult {
	if x != nil {
		return x.WinchResult
	}
	return nil
}

type RateControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      uint32                 `protobuf:"varint,1,opt,name=instance,proto3" json:"instance,omitempty"`
	RateMS        float32                `protobuf:"fixed32,2,opt,name=rate_m_s,json=rateMS,proto3" json:"rate_m_s,omitempty"` // Rate at which to wind or unwind the line
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateControlRequest) Reset() {
	*x = RateControlRequest{}
	mi := &file_winch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateControlRequest) ProtoMessage() {}

func (x *RateControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateControlRequest.ProtoReflect.Descriptor instead.
func (*RateControlRequest) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{8}
}

func (x *RateControlRequest) GetInstance() uint32 {
	if x != nil {
		return x.Instance
	}
	return 0
}

func (x *RateControlRequest) GetRateMS() float32 {
	if x != nil {
		return x.RateMS
	}
	return 0
}

type RateControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinchResult   *WinchResult           `protobuf:"bytes,1,opt,name=winch_result,json=winchResult,proto3" json:"winch_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateControlResponse) Reset() {
	*x = RateControlResponse{}
	mi := &file_winch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateControlResponse) ProtoMessage() {}

func (x *RateControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateControlResponse.ProtoReflect.Descriptor instead.
func (*RateControlResponse) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{9}
}

func (x *RateControlResponse) GetWinchResult() *WinchResult {
	if x != nil {
		return x.WinchResult
	}
	return nil
}

type LockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      uint32                 `protobuf:"varint,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockRequest) Reset() {
	*x = LockRequest{}
	mi := &file_winch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRequest) ProtoMessage() {}

func (x *LockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRequest.ProtoReflect.Descriptor instead.
func (*LockRequest) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{10}
}

func (x *LockRequest) GetInstance() uint32 {
	if x != nil {
		return x.Instance
	}
	return 0
}

type LockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinchResult   *WinchResult           `protobuf:"bytes,1,opt,name=winch_result,json=winchResult,proto3" json:"winch_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockResponse) Reset() {
	*x = LockResponse{}
	mi := &file_winch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockResponse) ProtoMessage() {}

func (x *LockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockResponse.ProtoReflect.Descriptor instead.
func (*LockResponse) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{11}
}

func (x *LockResponse) GetWinchResult() *WinchResult {
	if x != nil {
		return x.WinchResult
	}
	return nil
}

type DeliverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      uint32                 `protobuf:"varint,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRequest) Reset() {
	*x = DeliverRequest{}
	mi := &file_winch_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRequest) ProtoMessage() {}

func (x *DeliverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRequest.ProtoReflect.Descriptor instead.
func (*DeliverRequest) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{12}
}

func (x *DeliverRequest) GetInstance() uint32 {
	if x != nil {
		return x.Instance
	}
	return 0
}

type DeliverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinchResult   *WinchResult           `protobuf:"bytes,1,opt,name=winch_result,json=winchResult,proto3" json:"winch_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverResponse) Reset() {
	*x = DeliverResponse{}
	mi := &file_winch_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverResponse) ProtoMessage() {}

func (x *DeliverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverResponse.ProtoReflect.Descriptor instead.
func (*DeliverResponse) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{13}
}

func (x *DeliverResponse) GetWinchResult() *WinchResult {
	if x != nil {
		return x.WinchResult
	}
	return nil
}

type HoldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      uint32                 `protobuf:"varint,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldRequest) Reset() {
	*x = HoldRequest{}
	mi := &file_winch_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldRequest) ProtoMessage() {}

func (x *HoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldRequest.ProtoReflect.Descriptor instead.
func (*HoldRequest) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{14}
}

func (x *HoldRequest) GetInstance() uint32 {
	if x != nil {
		return x.Instance
	}
	return 0
}

type HoldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinchResult   *WinchResult           `protobuf:"bytes,1,opt,name=winch_result,json=winchResult,proto3" json:"winch_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HoldResponse) Reset() {
	*x = HoldResponse{}
	mi := &file_winch_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldResponse) ProtoMessage() {}

func (x *HoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldResponse.ProtoReflect.Descriptor instead.
func (*HoldResponse) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{15}
}

func (x *HoldResponse) GetWinchResult() *WinchResult {
	if x != nil {
		return x.WinchResult
	}
	return nil
}

type RetractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      uint32                 `protobuf:"varint,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetractRequest) Reset() {
	*x = RetractRequest{}
	mi := &file_winch_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetractRequest) ProtoMessage() {}

func (x *RetractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetractRequest.ProtoReflect.Descriptor instead.
func (*RetractRequest) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{16}
}

func (x *RetractRequest) GetInstance() uint32 {
	if x != nil {
		return x.Instance
	}
	return 0
}

type RetractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinchResult   *WinchResult           `protobuf:"bytes,1,opt,name=winch_result,json=winchResult,proto3" json:"winch_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetractResponse) Reset() {
	*x = RetractResponse{}
	mi := &file_winch_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetractResponse) ProtoMessage() {}

func (x *RetractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetractResponse.ProtoReflect.Descriptor instead.
func (*RetractResponse) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{17}
}

func (x *RetractResponse) GetWinchResult() *WinchResult {
	if x != nil {
		return x.WinchResult
	}
	return nil
}

type LoadLineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      uint32                 `protobuf:"varint,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadLineRequest) Reset() {
	*x = LoadLineRequest{}
	mi := &file_winch_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadLineRequest) ProtoMessage() {}

func (x *LoadLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadLineRequest.ProtoReflect.Descriptor instead.
func (*LoadLineRequest) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{18}
}

func (x *LoadLineRequest) GetInstance() uint32 {
	if x != nil {
		return x.Instance
	}
	return 0
}

type LoadLineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinchResult   *WinchResult           `protobuf:"bytes,1,opt,name=winch_result,json=winchResult,proto3" json:"winch_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadLineResponse) Reset() {
	*x = LoadLineResponse{}
	mi := &file_winch_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadLineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadLineResponse) ProtoMessage() {}

func (x *LoadLineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadLineResponse.ProtoReflect.Descriptor instead.
func (*LoadLineResponse) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{19}
}

func (x *LoadLineResponse) GetWinchResult() *WinchResult {
	if x != nil {
		return x.WinchResult
	}
	return nil
}

type AbandonLineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      uint32                 `protobuf:"varint,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbandonLineRequest) Reset() {
	*x = AbandonLineRequest{}
	mi := &file_winch_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonLineRequest) ProtoMessage() {}

func (x *AbandonLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonLineRequest.ProtoReflect.Descriptor instead.
func (*AbandonLineRequest) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{20}
}

func (x *AbandonLineRequest) GetInstance() uint32 {
	if x != nil {
		return x.Instance
	}
	return 0
}

type AbandonLineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinchResult   *WinchResult           `protobuf:"bytes,1,opt,name=winch_result,json=winchResult,proto3" json:"winch_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbandonLineResponse) Reset() {
	*x = AbandonLineResponse{}
	mi := &file_winch_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonLineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonLineResponse) ProtoMessage() {}

func (x *AbandonLineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonLineResponse.ProtoReflect.Descriptor instead.
func (*AbandonLineResponse) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{21}
}

func (x *AbandonLineResponse) GetWinchResult() *WinchResult {
	if x != nil {
		return x.WinchResult
	}
	return nil
}

type LoadPayloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      uint32                 `protobuf:"varint,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadPayloadRequest) Reset() {
	*x = LoadPayloadRequest{}
	mi := &file_winch_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadPayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadPayloadRequest) ProtoMessage() {}

func (x *LoadPayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadPayloadRequest.ProtoReflect.Descriptor instead.
func (*LoadPayloadRequest) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{22}
}

func (x *LoadPayloadRequest) GetInstance() uint32 {
	if x != nil {
		return x.Instance
	}
	return 0
}

type LoadPayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinchResult   *WinchResult           `protobuf:"bytes,1,opt,name=winch_result,json=winchResult,proto3" json:"winch_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadPayloadResponse) Reset() {
	*x = LoadPayloadResponse{}
	mi := &file_winch_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadPayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadPayloadResponse) ProtoMessage() {}

func (x *LoadPayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadPayloadResponse.ProtoReflect.Descriptor instead.
func (*LoadPayloadResponse) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{23}
}

func (x *LoadPayloadResponse) GetWinchResult() *WinchResult {
	if x != nil {
		return x.WinchResult
	}
	return nil
}

// Result type.
type WinchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        WinchResult_Result     `protobuf:"varint,1,opt,name=result,proto3,enum=mavsdk.rpc.winch.WinchResult_Result" json:"result,omitempty"` // Result enum value
	ResultStr     string                 `protobuf:"bytes,2,opt,name=result_str,json=resultStr,proto3" json:"result_str,omitempty"`                    // Human-readable English string describing the result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WinchResult) Reset() {
	*x = WinchResult{}
	mi := &file_winch_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WinchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WinchResult) ProtoMessage() {}

func (x *WinchResult) ProtoReflect() protoreflect.Message {
	mi := &file_winch_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WinchResult.ProtoReflect.Descriptor instead.
func (*WinchResult) Descriptor() ([]byte, []int) {
	return file_winch_proto_rawDescGZIP(), []int{24}
}

func (x *WinchResult) GetResult() WinchResult_Result {
	if x != nil {
		return x.Result
	}
	return WinchResult_RESULT_UNKNOWN
}

func (x *WinchResult) GetResultStr() string {
	if x != nil {
		return x.ResultStr
	}
	return ""
}

var File_winch_proto protoreflect.FileDescriptor

const file_winch_proto_rawDesc = "" +
	"\n" +
	"\vwinch.proto\x12\x10mavsdk.rpc.winch\x1a\x14mavsdk_options.proto\"\x18\n" +
	"\x16SubscribeStatusRequest\"B\n" +
	"\x0eStatusResponse\x120\n" +
	"\x06status\x18\x01 \x01(\v2\x18.mavsdk.rpc.winch.StatusR\x06status\"\xbf\x03\n" +
	"\vStatusFlags\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12'\n" +
	"\x0ffully_retracted\x18\x02 \x01(\bR\x0efullyRetracted\x12\x16\n" +
	"\x06moving\x18\x03 \x01(\bR\x06moving\x12%\n" +
	"\x0eclutch_engaged\x18\x04 \x01(\bR\rclutchEngaged\x12\x16\n" +
	"\x06locked\x18\x05 \x01(\bR\x06locked\x12\x1a\n" +
	"\bdropping\x18\x06 \x01(\bR\bdropping\x12\x1c\n" +
	"\tarresting\x18\a \x01(\bR\tarresting\x12!\n" +
	"\fground_sense\x18\b \x01(\bR\vgroundSense\x12\x1e\n" +
	"\n" +
	"retracting\x18\t \x01(\bR\n" +
	"retracting\x12\x1c\n" +
	"\tredeliver\x18\n" +
	" \x01(\bR\tredeliver\x12!\n" +
	"\fabandon_line\x18\v \x01(\bR\vabandonLine\x12\x18\n" +
	"\alocking\x18\f \x01(\bR\alocking\x12\x1b\n" +
	"\tload_line\x18\r \x01(\bR\bloadLine\x12!\n" +
	"\fload_payload\x18\x0e \x01(\bR\vloadPayload\"\xa5\x02\n" +
	"\x06Status\x12\x1b\n" +
	"\ttime_usec\x18\x01 \x01(\x04R\btimeUsec\x12\"\n" +
	"\rline_length_m\x18\x02 \x01(\x02R\vlineLengthM\x12\x1a\n" +
	"\tspeed_m_s\x18\x03 \x01(\x02R\aspeedMS\x12\x1d\n" +
	"\n" +
	"tension_kg\x18\x04 \x01(\x02R\ttensionKg\x12\x1b\n" +
	"\tvoltage_v\x18\x05 \x01(\x02R\bvoltageV\x12\x1b\n" +
	"\tcurrent_a\x18\x06 \x01(\x02R\bcurrentA\x12#\n" +
	"\rtemperature_c\x18\a \x01(\x05R\ftemperatureC\x12@\n" +
	"\fstatus_flags\x18\b \x01(\v2\x1d.mavsdk.rpc.winch.StatusFlagsR\vstatusFlags\"*\n" +
	"\fRelaxRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\rR\binstance\"Q\n" +
	"\rRelaxResponse\x12@\n" +
	"\fwinch_result\x18\x01 \x01(\v2\x1d.mavsdk.rpc.winch.WinchResultR\vwinchResult\"x\n" +
	"\x1cRelativeLengthControlRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\rR\binstance\x12\x19\n" +
	"\blength_m\x18\x02 \x01(\x02R\alengthM\x12!\n" +
	"\brate_m_s\x18\x03 \x01(\x02B\a\x82\xb5\x18\x03NaNR\x06rateMS\"a\n" +
	"\x1dRelativeLengthControlResponse\x12@\n" +
	"\fwinch_result\x18\x01 \x01(\v2\x1d.mavsdk.rpc.winch.WinchResultR\vwinchResult\"J\n" +
	"\x12RateControlRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\rR\binstance\x12\x18\n" +
	"\brate_m_s\x18\x02 \x01(\x02R\x06rateMS\"W\n" +
	"\x13RateControlResponse\x12@\n" +
	"\fwinch_result\x18\x01 \x01(\v2\x1d.mavsdk.rpc.winch.WinchResultR\vwinchResult\")\n" +
	"\vLockRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\rR\binstance\"P\n" +
	"\fLockResponse\x12@\n" +
	"\fwinch_result\x18\x01 \x01(\v2\x1d.mavsdk.rpc.winch.WinchResultR\vwinchResult\",\n" +
	"\x0eDeliverRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\rR\binstance\"S\n" +
	"\x0fDeliverResponse\x12@\n" +
	"\fwinch_result\x18\x01 \x01(\v2\x1d.mavsdk.rpc.winch.WinchResultR\vwinchResult\")\n" +
	"\vHoldRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\rR\binstance\"P\n" +
	"\fHoldResponse\x12@\n" +
	"\fwinch_result\x18\x01 \x01(\v2\x1d.mavsdk.rpc.winch.WinchResultR\vwinchResult\",\n" +
	"\x0eRetractRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\rR\binstance\"S\n" +
	"\x0fRetractResponse\x12@\n" +
	"\fwinch_result\x18\x01 \x01(\v2\x1d.mavsdk.rpc.winch.WinchResultR\vwinchResult\"-\n" +
	"\x0fLoadLineRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\rR\binstance\"T\n" +
	"\x10LoadLineResponse\x12@\n" +
	"\fwinch_result\x18\x01 \x01(\v2\x1d.mavsdk.rpc.winch.WinchResultR\vwinchResult\"0\n" +
	"\x12AbandonLineRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\rR\binstance\"W\n" +
	"\x13AbandonLineResponse\x12@\n" +
	"\fwinch_result\x18\x01 \x01(\v2\x1d.mavsdk.rpc.winch.WinchResultR\vwinchResult\"0\n" +
	"\x12LoadPayloadRequest\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\rR\binstance\"W\n" +
	"\x13LoadPayloadResponse\x12@\n" +
	"\fwinch_result\x18\x01 \x01(\v2\x1d.mavsdk.rpc.winch.WinchResultR\vwinchResult\"\x83\x02\n" +
	"\vWinchResult\x12<\n" +
	"\x06result\x18\x01 \x01(\x0e2$.mavsdk.rpc.winch.WinchResult.ResultR\x06result\x12\x1d\n" +
	"\n" +
	"result_str\x18\x02 \x01(\tR\tresultStr\"\x96\x01\n" +
	"\x06Result\x12\x12\n" +
	"\x0eRESULT_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eRESULT_SUCCESS\x10\x01\x12\x14\n" +
	"\x10RESULT_NO_SYSTEM\x10\x02\x12\x0f\n" +
	"\vRESULT_BUSY\x10\x03\x12\x12\n" +
	"\x0eRESULT_TIMEOUT\x10\x04\x12\x16\n" +
	"\x12RESULT_UNSUPPORTED\x10\x05\x12\x11\n" +
	"\rRESULT_FAILED\x10\x06*\xac\x02\n" +
	"\vWinchAction\x12\x18\n" +
	"\x14WINCH_ACTION_RELAXED\x10\x00\x12(\n" +
	"$WINCH_ACTION_RELATIVE_LENGTH_CONTROL\x10\x01\x12\x1d\n" +
	"\x19WINCH_ACTION_RATE_CONTROL\x10\x02\x12\x15\n" +
	"\x11WINCH_ACTION_LOCK\x10\x03\x12\x18\n" +
	"\x14WINCH_ACTION_DELIVER\x10\x04\x12\x15\n" +
	"\x11WINCH_ACTION_HOLD\x10\x05\x12\x18\n" +
	"\x14WINCH_ACTION_RETRACT\x10\x06\x12\x1a\n" +
	"\x16WINCH_ACTION_LOAD_LINE\x10\a\x12\x1d\n" +
	"\x19WINCH_ACTION_ABANDON_LINE\x10\b\x12\x1d\n" +
	"\x19WINCH_ACTION_LOAD_PAYLOAD\x10\t2\xde\a\n" +
	"\fWinchService\x12a\n" +
	"\x0fSubscribeStatus\x12(.mavsdk.rpc.winch.SubscribeStatusRequest\x1a .mavsdk.rpc.winch.StatusResponse\"\x000\x01\x12J\n" +
	"\x05Relax\x12\x1e.mavsdk.rpc.winch.RelaxRequest\x1a\x1f.mavsdk.rpc.winch.RelaxResponse\"\x00\x12z\n" +
	"\x15RelativeLengthControl\x12..mavsdk.rpc.winch.RelativeLengthControlRequest\x1a/.mavsdk.rpc.winch.RelativeLengthControlResponse\"\x00\x12\\\n" +
	"\vRateControl\x12$.mavsdk.rpc.winch.RateControlRequest\x1a%.mavsdk.rpc.winch.RateControlResponse\"\x00\x12G\n" +
	"\x04Lock\x12\x1d.mavsdk.rpc.winch.LockRequest\x1a\x1e.mavsdk.rpc.winch.LockResponse\"\x00\x12P\n" +
	"\aDeliver\x12 .mavsdk.rpc.winch.DeliverRequest\x1a!.mavsdk.rpc.winch.DeliverResponse\"\x00\x12G\n" +
	"\x04Hold\x12\x1d.mavsdk.rpc.winch.HoldRequest\x1a\x1e.mavsdk.rpc.winch.HoldResponse\"\x00\x12P\n" +
	"\aRetract\x12 .mavsdk.rpc.winch.RetractRequest\x1a!.mavsdk.rpc.winch.RetractResponse\"\x00\x12S\n" +
	"\bLoadLine\x12!.mavsdk.rpc.winch.LoadLineRequest\x1a\".mavsdk.rpc.winch.LoadLineResponse\"\x00\x12\\\n" +
	"\vAbandonLine\x12$.mavsdk.rpc.winch.AbandonLineRequest\x1a%.mavsdk.rpc.winch.AbandonLineResponse\"\x00\x12\\\n" +
	"\vLoadPayload\x12$.mavsdk.rpc.winch.LoadPayloadRequest\x1a%.mavsdk.rpc.winch.LoadPayloadResponse\"\x00B\x15B\n" +
	"WinchProtoZ\a.;winchb\x06proto3"

var (
	file_winch_proto_rawDescOnce sync.Once
	file_winch_proto_rawDescData []byte
)

func file_winch_proto_rawDescGZIP() []byte {
	file_winch_proto_rawDescOnce.Do(func() {
		file_winch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_winch_proto_rawDesc), len(file_winch_proto_rawDesc)))
	})
	return file_winch_proto_rawDescData
}

var file_winch_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_winch_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_winch_proto_goTypes = []any{
	(WinchAction)(0),                      // 0: mavsdk.rpc.winch.WinchAction
	(WinchResult_Result)(0),               // 1: mavsdk.rpc.winch.WinchResult.Result
	(*SubscribeStatusRequest)(nil),        // 2: mavsdk.rpc.winch.SubscribeStatusRequest
	(*StatusResponse)(nil),                // 3: mavsdk.rpc.winch.StatusResponse
	(*StatusFlags)(nil),                   // 4: mavsdk.rpc.winch.StatusFlags
	(*Status)(nil),                        // 5: mavsdk.rpc.winch.Status
	(*RelaxRequest)(nil),                  // 6: mavsdk.rpc.winch.RelaxRequest
	(*RelaxResponse)(nil),                 // 7: mavsdk.rpc.winch.RelaxResponse
	(*RelativeLengthControlRequest)(nil),  // 8: mavsdk.rpc.winch.RelativeLengthControlRequest
	(*RelativeLengthControlResponse)(nil), // 9: mavsdk.rpc.winch.RelativeLengthControlResponse
	(*RateControlRequest)(nil),            // 10: mavsdk.rpc.winch.RateControlRequest
	(*RateControlResponse)(nil),           // 11: mavsdk.rpc.winch.RateControlResponse
	(*LockRequest)(nil),                   // 12: mavsdk.rpc.winch.LockRequest
	(*LockResponse)(nil),                  // 13: mavsdk.rpc.winch.LockResponse
	(*DeliverRequest)(nil),                // 14: mavsdk.rpc.winch.DeliverRequest
	(*DeliverResponse)(nil),               // 15: mavsdk.rpc.winch.DeliverResponse
	(*HoldRequest)(nil),                   // 16: mavsdk.rpc.winch.HoldRequest
	(*HoldResponse)(nil),                  // 17: mavsdk.rpc.winch.HoldResponse
	(*RetractRequest)(nil),                // 18: mavsdk.rpc.winch.RetractRequest
	(*RetractResponse)(nil),               // 19: mavsdk.rpc.winch.RetractResponse
	(*LoadLineRequest)(nil),               // 20: mavsdk.rpc.winch.LoadLineRequest
	(*LoadLineResponse)(nil),              // 21: mavsdk.rpc.winch.LoadLineResponse
	(*AbandonLineRequest)(nil),            // 22: mavsdk.rpc.winch.AbandonLineRequest
	(*AbandonLineResponse)(nil),           // 23: mavsdk.rpc.winch.AbandonLineResponse
	(*LoadPayloadRequest)(nil),            // 24: mavsdk.rpc.winch.LoadPayloadRequest
	(*LoadPayloadResponse)(nil),           // 25: mavsdk.rpc.winch.LoadPayloadResponse
	(*WinchResult)(nil),                   // 26: mavsdk.rpc.winch.WinchResult
}
var file_winch_proto_depIdxs = []int32{
	5,  // 0: mavsdk.rpc.winch.StatusResponse.status:type_name -> mavsdk.rpc.winch.Status
	4,  // 1: mavsdk.rpc.winch.Status.status_flags:type_name -> mavsdk.rpc.winch.StatusFlags
	26, // 2: mavsdk.rpc.winch.RelaxResponse.winch_result:type_name -> mavsdk.rpc.winch.WinchResult
	26, // 3: mavsdk.rpc.winch.RelativeLengthControlResponse.winch_result:type_name -> mavsdk.rpc.winch.WinchResult
	26, // 4: mavsdk.rpc.winch.RateControlResponse.winch_result:type_name -> mavsdk.rpc.winch.WinchResult
	26, // 5: mavsdk.rpc.winch.LockResponse.winch_result:type_name -> mavsdk.rpc.winch.WinchResult
	26, // 6: mavsdk.rpc.winch.DeliverResponse.winch_result:type_name -> mavsdk.rpc.winch.WinchResult
	26, // 7: mavsdk.rpc.winch.HoldResponse.winch_result:type_name -> mavsdk.rpc.winch.WinchResult
	26, // 8: mavsdk.rpc.winch.RetractResponse.winch_result:type_name -> mavsdk.rpc.winch.WinchResult
	26, // 9: mavsdk.rpc.winch.LoadLineResponse.winch_result:type_name -> mavsdk.rpc.winch.WinchResult
	26, // 10: mavsdk.rpc.winch.AbandonLineResponse.winch_result:type_name -> mavsdk.rpc.winch.WinchResult
	26, // 11: mavsdk.rpc.winch.LoadPayloadResponse.winch_result:type_name -> mavsdk.rpc.winch.WinchResult
	1,  // 12: mavsdk.rpc.winch.WinchResult.result:type_name -> mavsdk.rpc.winch.WinchResult.Result
	2,  // 13: mavsdk.rpc.winch.WinchService.SubscribeStatus:input_type -> mavsdk.rpc.winch.SubscribeStatusRequest
	6,  // 14: mavsdk.rpc.winch.WinchService.Relax:input_type -> mavsdk.rpc.winch.RelaxRequest
	8,  // 15: mavsdk.rpc.winch.WinchService.RelativeLengthControl:input_type -> mavsdk.rpc.winch.RelativeLengthControlRequest
	10, // 16: mavsdk.rpc.winch.WinchService.RateControl:input_type -> mavsdk.rpc.winch.RateControlRequest
	12, // 17: mavsdk.rpc.winch.WinchService.Lock:input_type -> mavsdk.rpc.winch.LockRequest
	14, // 18: mavsdk.rpc.winch.WinchService.Deliver:input_type -> mavsdk.rpc.winch.DeliverRequest
	16, // 19: mavsdk.rpc.winch.WinchService.Hold:input_type -> mavsdk.rpc.winch.HoldRequest
	18, // 20: mavsdk.rpc.winch.WinchService.Retract:input_type -> mavsdk.rpc.winch.RetractRequest
	20, // 21: mavsdk.rpc.winch.WinchService.LoadLine:input_type -> mavsdk.rpc.winch.LoadLineRequest
	22, // 22: mavsdk.rpc.winch.WinchService.AbandonLine:input_type -> mavsdk.rpc.winch.AbandonLineRequest
	24, // 23: mavsdk.rpc.winch.WinchService.LoadPayload:input_type -> mavsdk.rpc.winch.LoadPayloadRequest
	3,  // 24: mavsdk.rpc.winch.WinchService.SubscribeStatus:output_type -> mavsdk.rpc.winch.StatusResponse
	7,  // 25: mavsdk.rpc.winch.WinchService.Relax:output_type -> mavsdk.rpc.winch.RelaxResponse
	9,  // 26: mavsdk.rpc.winch.WinchService.RelativeLengthControl:output_type -> mavsdk.rpc.winch.RelativeLengthControlResponse
	11, // 27: mavsdk.rpc.winch.WinchService.RateControl:output_type -> mavsdk.rpc.winch.RateControlResponse
	13, // 28: mavsdk.rpc.winch.WinchService.Lock:output_type -> mavsdk.rpc.winch.LockResponse
	15, // 29: mavsdk.rpc.winch.WinchService.Deliver:output_type -> mavsdk.rpc.winch.DeliverResponse
	17, // 30: mavsdk.rpc.winch.WinchService.Hold:output_type -> mavsdk.rpc.winch.HoldResponse
	19, // 31: mavsdk.rpc.winch.WinchService.Retract:output_type -> mavsdk.rpc.winch.RetractResponse
	21, // 32: mavsdk.rpc.winch.WinchService.LoadLine:output_type -> mavsdk.rpc.winch.LoadLineResponse
	23, // 33: mavsdk.rpc.winch.WinchService.AbandonLine:output_type -> mavsdk.rpc.winch.AbandonLineResponse
	25, // 34: mavsdk.rpc.winch.WinchService.LoadPayload:output_type -> mavsdk.rpc.winch.LoadPayloadResponse
	24, // [24:35] is the sub-list for method output_type
	13, // [13:24] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_winch_proto_init() }
func file_winch_proto_init() {
	if File_winch_proto != nil {
		return
	}
	file_mavsdk_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_winch_proto_rawDesc), len(file_winch_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_winch_proto_goTypes,
		DependencyIndexes: file_winch_proto_depIdxs,
		EnumInfos:         file_winch_proto_enumTypes,
		MessageInfos:      file_winch_proto_msgTypes,
	}.Build()
	File_winch_proto = out.File
	file_winch_proto_goTypes = nil
	file_winch_proto_depIdxs = nil
}
