// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.15.2
// source: param.proto

package param

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Possible results returned for param requests.
type ParamResult_Result int32

const (
	ParamResult_RESULT_UNKNOWN             ParamResult_Result = 0 // Unknown result
	ParamResult_RESULT_SUCCESS             ParamResult_Result = 1 // Request succeeded
	ParamResult_RESULT_TIMEOUT             ParamResult_Result = 2 // Request timed out
	ParamResult_RESULT_CONNECTION_ERROR    ParamResult_Result = 3 // Connection error
	ParamResult_RESULT_WRONG_TYPE          ParamResult_Result = 4 // Wrong type
	ParamResult_RESULT_PARAM_NAME_TOO_LONG ParamResult_Result = 5 // Parameter name too long (> 16)
)

// Enum value maps for ParamResult_Result.
var (
	ParamResult_Result_name = map[int32]string{
		0: "RESULT_UNKNOWN",
		1: "RESULT_SUCCESS",
		2: "RESULT_TIMEOUT",
		3: "RESULT_CONNECTION_ERROR",
		4: "RESULT_WRONG_TYPE",
		5: "RESULT_PARAM_NAME_TOO_LONG",
	}
	ParamResult_Result_value = map[string]int32{
		"RESULT_UNKNOWN":             0,
		"RESULT_SUCCESS":             1,
		"RESULT_TIMEOUT":             2,
		"RESULT_CONNECTION_ERROR":    3,
		"RESULT_WRONG_TYPE":          4,
		"RESULT_PARAM_NAME_TOO_LONG": 5,
	}
)

func (x ParamResult_Result) Enum() *ParamResult_Result {
	p := new(ParamResult_Result)
	*p = x
	return p
}

func (x ParamResult_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParamResult_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_param_proto_enumTypes[0].Descriptor()
}

func (ParamResult_Result) Type() protoreflect.EnumType {
	return &file_param_proto_enumTypes[0]
}

func (x ParamResult_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParamResult_Result.Descriptor instead.
func (ParamResult_Result) EnumDescriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{8, 0}
}

type GetParamIntRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name of the parameter
}

func (x *GetParamIntRequest) Reset() {
	*x = GetParamIntRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParamIntRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParamIntRequest) ProtoMessage() {}

func (x *GetParamIntRequest) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParamIntRequest.ProtoReflect.Descriptor instead.
func (*GetParamIntRequest) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{0}
}

func (x *GetParamIntRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetParamIntResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParamResult *ParamResult `protobuf:"bytes,1,opt,name=param_result,json=paramResult,proto3" json:"param_result,omitempty"`
	Value       int32        `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"` // Value of the requested parameter
}

func (x *GetParamIntResponse) Reset() {
	*x = GetParamIntResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParamIntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParamIntResponse) ProtoMessage() {}

func (x *GetParamIntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParamIntResponse.ProtoReflect.Descriptor instead.
func (*GetParamIntResponse) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{1}
}

func (x *GetParamIntResponse) GetParamResult() *ParamResult {
	if x != nil {
		return x.ParamResult
	}
	return nil
}

func (x *GetParamIntResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SetParamIntRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`    // Name of the parameter to set
	Value int32  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"` // Value the parameter should be set to
}

func (x *SetParamIntRequest) Reset() {
	*x = SetParamIntRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetParamIntRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetParamIntRequest) ProtoMessage() {}

func (x *SetParamIntRequest) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetParamIntRequest.ProtoReflect.Descriptor instead.
func (*SetParamIntRequest) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{2}
}

func (x *SetParamIntRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetParamIntRequest) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SetParamIntResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParamResult *ParamResult `protobuf:"bytes,1,opt,name=param_result,json=paramResult,proto3" json:"param_result,omitempty"`
}

func (x *SetParamIntResponse) Reset() {
	*x = SetParamIntResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetParamIntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetParamIntResponse) ProtoMessage() {}

func (x *SetParamIntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetParamIntResponse.ProtoReflect.Descriptor instead.
func (*SetParamIntResponse) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{3}
}

func (x *SetParamIntResponse) GetParamResult() *ParamResult {
	if x != nil {
		return x.ParamResult
	}
	return nil
}

type GetParamFloatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name of the parameter
}

func (x *GetParamFloatRequest) Reset() {
	*x = GetParamFloatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParamFloatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParamFloatRequest) ProtoMessage() {}

func (x *GetParamFloatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParamFloatRequest.ProtoReflect.Descriptor instead.
func (*GetParamFloatRequest) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{4}
}

func (x *GetParamFloatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetParamFloatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParamResult *ParamResult `protobuf:"bytes,1,opt,name=param_result,json=paramResult,proto3" json:"param_result,omitempty"`
	Value       float32      `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"` // Value of the requested parameter
}

func (x *GetParamFloatResponse) Reset() {
	*x = GetParamFloatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParamFloatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParamFloatResponse) ProtoMessage() {}

func (x *GetParamFloatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParamFloatResponse.ProtoReflect.Descriptor instead.
func (*GetParamFloatResponse) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{5}
}

func (x *GetParamFloatResponse) GetParamResult() *ParamResult {
	if x != nil {
		return x.ParamResult
	}
	return nil
}

func (x *GetParamFloatResponse) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SetParamFloatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     // Name of the parameter to set
	Value float32 `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"` // Value the parameter should be set to
}

func (x *SetParamFloatRequest) Reset() {
	*x = SetParamFloatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetParamFloatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetParamFloatRequest) ProtoMessage() {}

func (x *SetParamFloatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetParamFloatRequest.ProtoReflect.Descriptor instead.
func (*SetParamFloatRequest) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{6}
}

func (x *SetParamFloatRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetParamFloatRequest) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SetParamFloatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParamResult *ParamResult `protobuf:"bytes,1,opt,name=param_result,json=paramResult,proto3" json:"param_result,omitempty"`
}

func (x *SetParamFloatResponse) Reset() {
	*x = SetParamFloatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetParamFloatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetParamFloatResponse) ProtoMessage() {}

func (x *SetParamFloatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetParamFloatResponse.ProtoReflect.Descriptor instead.
func (*SetParamFloatResponse) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{7}
}

func (x *SetParamFloatResponse) GetParamResult() *ParamResult {
	if x != nil {
		return x.ParamResult
	}
	return nil
}

// Result type.
type ParamResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result    ParamResult_Result `protobuf:"varint,1,opt,name=result,proto3,enum=mavsdk.rpc.param.ParamResult_Result" json:"result,omitempty"` // Result enum value
	ResultStr string             `protobuf:"bytes,2,opt,name=result_str,json=resultStr,proto3" json:"result_str,omitempty"`                    // Human-readable English string describing the result
}

func (x *ParamResult) Reset() {
	*x = ParamResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_param_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParamResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamResult) ProtoMessage() {}

func (x *ParamResult) ProtoReflect() protoreflect.Message {
	mi := &file_param_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamResult.ProtoReflect.Descriptor instead.
func (*ParamResult) Descriptor() ([]byte, []int) {
	return file_param_proto_rawDescGZIP(), []int{8}
}

func (x *ParamResult) GetResult() ParamResult_Result {
	if x != nil {
		return x.Result
	}
	return ParamResult_RESULT_UNKNOWN
}

func (x *ParamResult) GetResultStr() string {
	if x != nil {
		return x.ResultStr
	}
	return ""
}

var File_param_proto protoreflect.FileDescriptor

var file_param_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6d,
	0x61, 0x76, 0x73, 0x64, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x1a,
	0x14, 0x6d, 0x61, 0x76, 0x73, 0x64, 0x6b, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x6d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0c, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x5f,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d,
	0x61, 0x76, 0x73, 0x64, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x2e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0b, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3e,
	0x0a, 0x12, 0x53, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x57,
	0x0a, 0x13, 0x53, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0c, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x5f, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61,
	0x76, 0x73, 0x64, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x2e, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0b, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x2a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x6f, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x46,
	0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0c,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x76, 0x73, 0x64, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x0b, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x40, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x59, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x40, 0x0a, 0x0c, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x76, 0x73, 0x64, 0x6b, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x0b, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x85, 0x02, 0x0a, 0x0b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x3c, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x24, 0x2e, 0x6d, 0x61, 0x76, 0x73, 0x64, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x53, 0x74, 0x72, 0x22, 0x98,
	0x01, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x53,
	0x55, 0x4c, 0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x12, 0x0a,
	0x0e, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10,
	0x01, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x54, 0x49, 0x4d, 0x45,
	0x4f, 0x55, 0x54, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f,
	0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x57, 0x52, 0x4f,
	0x4e, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x04, 0x12, 0x1e, 0x0a, 0x1a, 0x52, 0x45, 0x53,
	0x55, 0x4c, 0x54, 0x5f, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x5f, 0x54,
	0x4f, 0x4f, 0x5f, 0x4c, 0x4f, 0x4e, 0x47, 0x10, 0x05, 0x32, 0xa2, 0x03, 0x0a, 0x0c, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x6e, 0x74, 0x12, 0x24, 0x2e, 0x6d, 0x61, 0x76, 0x73,
	0x64, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x6d, 0x61, 0x76, 0x73, 0x64, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x04, 0x80, 0xb5, 0x18, 0x01, 0x12, 0x60, 0x0a, 0x0b,
	0x53, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x6e, 0x74, 0x12, 0x24, 0x2e, 0x6d, 0x61,
	0x76, 0x73, 0x64, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x2e, 0x53,
	0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x25, 0x2e, 0x6d, 0x61, 0x76, 0x73, 0x64, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x2e, 0x53, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x49, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x04, 0x80, 0xb5, 0x18, 0x01, 0x12, 0x66,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12,
	0x26, 0x2e, 0x6d, 0x61, 0x76, 0x73, 0x64, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x46, 0x6c, 0x6f, 0x61, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6d, 0x61, 0x76, 0x73, 0x64, 0x6b,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x04, 0x80, 0xb5, 0x18, 0x01, 0x12, 0x66, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x26, 0x2e, 0x6d, 0x61, 0x76, 0x73, 0x64, 0x6b,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x2e, 0x53, 0x65, 0x74, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x27, 0x2e, 0x6d, 0x61, 0x76, 0x73, 0x64, 0x6b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x2e, 0x53, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x46, 0x6c, 0x6f, 0x61, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x04, 0x80, 0xb5, 0x18, 0x01, 0x42, 0x15,
	0x42, 0x0a, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x07, 0x2e, 0x3b,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_param_proto_rawDescOnce sync.Once
	file_param_proto_rawDescData = file_param_proto_rawDesc
)

func file_param_proto_rawDescGZIP() []byte {
	file_param_proto_rawDescOnce.Do(func() {
		file_param_proto_rawDescData = protoimpl.X.CompressGZIP(file_param_proto_rawDescData)
	})
	return file_param_proto_rawDescData
}

var file_param_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_param_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_param_proto_goTypes = []interface{}{
	(ParamResult_Result)(0),       // 0: mavsdk.rpc.param.ParamResult.Result
	(*GetParamIntRequest)(nil),    // 1: mavsdk.rpc.param.GetParamIntRequest
	(*GetParamIntResponse)(nil),   // 2: mavsdk.rpc.param.GetParamIntResponse
	(*SetParamIntRequest)(nil),    // 3: mavsdk.rpc.param.SetParamIntRequest
	(*SetParamIntResponse)(nil),   // 4: mavsdk.rpc.param.SetParamIntResponse
	(*GetParamFloatRequest)(nil),  // 5: mavsdk.rpc.param.GetParamFloatRequest
	(*GetParamFloatResponse)(nil), // 6: mavsdk.rpc.param.GetParamFloatResponse
	(*SetParamFloatRequest)(nil),  // 7: mavsdk.rpc.param.SetParamFloatRequest
	(*SetParamFloatResponse)(nil), // 8: mavsdk.rpc.param.SetParamFloatResponse
	(*ParamResult)(nil),           // 9: mavsdk.rpc.param.ParamResult
}
var file_param_proto_depIdxs = []int32{
	9, // 0: mavsdk.rpc.param.GetParamIntResponse.param_result:type_name -> mavsdk.rpc.param.ParamResult
	9, // 1: mavsdk.rpc.param.SetParamIntResponse.param_result:type_name -> mavsdk.rpc.param.ParamResult
	9, // 2: mavsdk.rpc.param.GetParamFloatResponse.param_result:type_name -> mavsdk.rpc.param.ParamResult
	9, // 3: mavsdk.rpc.param.SetParamFloatResponse.param_result:type_name -> mavsdk.rpc.param.ParamResult
	0, // 4: mavsdk.rpc.param.ParamResult.result:type_name -> mavsdk.rpc.param.ParamResult.Result
	1, // 5: mavsdk.rpc.param.ParamService.GetParamInt:input_type -> mavsdk.rpc.param.GetParamIntRequest
	3, // 6: mavsdk.rpc.param.ParamService.SetParamInt:input_type -> mavsdk.rpc.param.SetParamIntRequest
	5, // 7: mavsdk.rpc.param.ParamService.GetParamFloat:input_type -> mavsdk.rpc.param.GetParamFloatRequest
	7, // 8: mavsdk.rpc.param.ParamService.SetParamFloat:input_type -> mavsdk.rpc.param.SetParamFloatRequest
	2, // 9: mavsdk.rpc.param.ParamService.GetParamInt:output_type -> mavsdk.rpc.param.GetParamIntResponse
	4, // 10: mavsdk.rpc.param.ParamService.SetParamInt:output_type -> mavsdk.rpc.param.SetParamIntResponse
	6, // 11: mavsdk.rpc.param.ParamService.GetParamFloat:output_type -> mavsdk.rpc.param.GetParamFloatResponse
	8, // 12: mavsdk.rpc.param.ParamService.SetParamFloat:output_type -> mavsdk.rpc.param.SetParamFloatResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_param_proto_init() }
func file_param_proto_init() {
	if File_param_proto != nil {
		return
	}
	file_mavsdk_options_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_param_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParamIntRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParamIntResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetParamIntRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetParamIntResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParamFloatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParamFloatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetParamFloatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetParamFloatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_param_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParamResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_param_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_param_proto_goTypes,
		DependencyIndexes: file_param_proto_depIdxs,
		EnumInfos:         file_param_proto_enumTypes,
		MessageInfos:      file_param_proto_msgTypes,
	}.Build()
	File_param_proto = out.File
	file_param_proto_rawDesc = nil
	file_param_proto_goTypes = nil
	file_param_proto_depIdxs = nil
}
